#!/bin/bash

# This script could resume the execution if it failed at some point to take advantage of the fact the qsubs files (ie the files for pbs torque) are already pregenerated by the workflow anyway even if it fails.

# Just change what you ls!

ls qsub*realVcall* > qsubsscripts

readarray qsubs < qsubsscripts

rm qsubsscripts

i=0
while [ i -lt ${#qsubs}  ];
do
	qsub1=${qsubs[i]}
	qsub $qsub1
	let i+=1

done

